import { Inter } from "next/font/google";
import "./globals.css";
import CustomLink from "./components/CustomLink";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Home",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                {/* =====================nav======================== */}
                <nav className="bg-gray-500 p-5">
                    <ul className="flex space-x-5">
                        <li>
                            <CustomLink path="/">Home</CustomLink>
                        </li>
                        <li>
                            <CustomLink prefetch={false} path="/settings">
                                setting
                            </CustomLink>
                        </li>
                        <li>
                            <CustomLink path="/analytics">analytics</CustomLink>
                        </li>
                        <li>
                            <CustomLink path="/heavy">Heavy</CustomLink>
                        </li>
                        <li>
                            <CustomLink path="/blogs">Blogs</CustomLink>
                        </li>
                    </ul>
                </nav>
                {/* ======================nav======================= */}

                {children}
            </body>
        </html>
    );
}
