import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Home",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                {/* =====================nav======================== */}
                <nav className="bg-blue-500 p-5">
                    <ul className="flex space-x-5">
                        <li>
                            <Link href="/">Home</Link>
                        </li>
                        <li>
                            <Link href="/dasboard/settings">setting</Link>
                        </li>
                        <li>
                            <Link href="/dasboard/analytics">analytics</Link>
                        </li>
                    </ul>
                </nav>
                {/* ======================nav======================= */}

                {children}
            </body>
        </html>
    );
}
