import React from "react";

export const metadata = {
    title: "Analytics",
    description: "Generated by create next app",
};
const page = () => {
    return (
        <div className="bg-red-400 p-10">
            <h1>Analytics page</h1>
            <p className="pt-10 ">
                Lorem ipsum dolor sit amet consectetur adipisicing elit.
                Pariatur esse dolor iusto debitis assumenda ratione! Aperiam
                laborum pariatur, eligendi veritatis sunt facilis molestiae
                tempore veniam, magnam harum illo repellendus ullam?
            </p>
        </div>
    );
};

export default page;
