import React from "react";

export const metadata = {
    title: "Analytics",
    description: "Generated by create next app",
};
const page = () => {
    return (
        <div className="bg-red-700 p-10 w-3/4 mx-auto mt-10">
            <h1 className="text-4xl text-center">Analytics page</h1>
            <p className="pt-10 ">
                Lorem ipsum dolor sit amet consectetur adipisicing elit.
                Pariatur esse dolor iusto debitis assumenda ratione! Aperiam
                laborum pariatur, eligendi veritatis sunt facilis molestiae
                tempore veniam, magnam harum illo repellendus ullam?
            </p>
        </div>
    );
};

export default page;
