import React from "react";

export const metadata = {
    title: "Settings",
    description: "Generated by create next app",
};

const Settings = () => {
    return (
        <div className="bg-green-300 p-5">
            <h1 className="text-2xl">Hello next.js</h1>
            <p className="pt-10 text-justify">
                Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                Suscipit doloribus esse omnis vel quis illum, placeat sequi
                adipisci excepturi labore? Blanditiis ea labore animi
                perferendis doloremque sit quas ullam nesciunt?
            </p>
        </div>
    );
};

export default Settings;
